<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XMLWRE0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XMLWRE0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XMLWRE0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'notification' => ['privates', '.errored..service_locator.XMLWRE0.App\\Entity\\Notification', NULL, 'Cannot autowire service ".service_locator.XMLWRE0": it needs an instance of "App\\Entity\\Notification" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'notification' => 'App\\Entity\\Notification',
        ]);
    }
}
