<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArchiveRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\ArchiveRepository' shared autowired service.
     *
     * @return \App\Repository\ArchiveRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Repository/ArchiveRepository.php';

        return $container->privates['App\\Repository\\ArchiveRepository'] = new \App\Repository\ArchiveRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
