<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckInactiveFileCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\CheckInactiveFileCommand' shared autowired service.
     *
     * @return \App\Command\CheckInactiveFileCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/CheckInactiveFileCommand.php';

        $container->privates['App\\Command\\CheckInactiveFileCommand'] = $instance = new \App\Command\CheckInactiveFileCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\DossiersRepository'] ?? self::getDossiersRepositoryService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('CheckInactiveFile');
        $instance->setDescription('Check for inactive dossiers and unlock them if necessary');

        return $instance;
    }
}
