<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommentairesTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CommentairesType' shared autowired service.
     *
     * @return \App\Form\CommentairesType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CommentairesType.php';

        return $container->privates['App\\Form\\CommentairesType'] = new \App\Form\CommentairesType();
    }
}
