<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiersSearchService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\DossiersSearch' autowired service.
     *
     * @return \App\Twig\Components\DossiersSearch
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/DossiersSearch.php';

        $container->factories['App\\Twig\\Components\\DossiersSearch'] = function ($container) {
            return new \App\Twig\Components\DossiersSearch(($container->privates['App\\Repository\\DossiersRepository'] ?? self::getDossiersRepositoryService($container)), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
        };

        return $container->factories['App\\Twig\\Components\\DossiersSearch']($container);
    }
}
