<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiersEditArchiveTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DossiersEditArchiveType' shared autowired service.
     *
     * @return \App\Form\DossiersEditArchiveType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DossiersEditArchiveType.php';

        return $container->privates['App\\Form\\DossiersEditArchiveType'] = new \App\Form\DossiersEditArchiveType(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\ClientsRepository'] ?? $container->load('getClientsRepositoryService')), ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container)));
    }
}
