<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiers2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ciSKRIx.App\Entity\Dossiers' shared service.
     *
     * @return \App\Entity\Dossiers
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.ciSKRIx": it needs an instance of "App\\Entity\\Dossiers" but this type has been excluded in "config/services.yaml".');
    }
}
