<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiersSearchTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\DossiersSearchType' shared autowired service.
     *
     * @return \App\Form\DossiersSearchType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/DossiersSearchType.php';

        return $container->privates['App\\Form\\DossiersSearchType'] = new \App\Form\DossiersSearchType();
    }
}
