<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossierVRPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Twig\Components\DossierVRP' autowired service.
     *
     * @return \App\Twig\Components\DossierVRP
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-live-component/src/DefaultActionTrait.php';
        include_once \dirname(__DIR__, 4).'/src/Twig/Components/DossierVRP.php';

        $container->factories['App\\Twig\\Components\\DossierVRP'] = function ($container) {
            $a = ($container->privates['security.helper'] ?? self::getSecurity_HelperService($container));

            if (isset($container->services['App\\Twig\\Components\\DossierVRP'])) {
                return $container->services['App\\Twig\\Components\\DossierVRP'];
            }

            return new \App\Twig\Components\DossierVRP(($container->privates['App\\Repository\\DossiersRepository'] ?? self::getDossiersRepositoryService($container)), $a);
        };

        return $container->factories['App\\Twig\\Components\\DossierVRP']($container);
    }
}
