<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormSubmissionProfilListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\FormSubmissionProfilListener' shared autowired service.
     *
     * @return \App\EventListener\FormSubmissionProfilListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/FormSubmissionProfilListener.php';

        return $container->privates['App\\EventListener\\FormSubmissionProfilListener'] = new \App\EventListener\FormSubmissionProfilListener(($container->services['cache.app'] ?? self::getCache_AppService($container)), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));
    }
}
