<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogoutEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\LogoutEventSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\LogoutEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/LogoutEventSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\LogoutEventSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\LogoutEventSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\LogoutEventSubscriber'] = new \App\EventSubscriber\LogoutEventSubscriber(($container->privates['App\\Repository\\DossiersRepository'] ?? self::getDossiersRepositoryService($container)), $a);
    }
}
