<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationCleanupCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\NotificationCleanupCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.App\\Command\\NotificationCleanupCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:notification:cleanup', [], 'Deletes notification from the database', false, #[\Closure(name: 'App\\Command\\NotificationCleanupCommand')] fn (): \App\Command\NotificationCleanupCommand => ($container->privates['App\\Command\\NotificationCleanupCommand'] ?? $container->load('getNotificationCleanupCommandService')));
    }
}
