<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationCleanupCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\NotificationCleanupCommand' shared autowired service.
     *
     * @return \App\Command\NotificationCleanupCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/NotificationCleanupCommand.php';

        $container->privates['App\\Command\\NotificationCleanupCommand'] = $instance = new \App\Command\NotificationCleanupCommand(($container->privates['App\\Repository\\NotificationRepository'] ?? $container->load('getNotificationRepositoryService')));

        $instance->setName('app:notification:cleanup');
        $instance->setDescription('Deletes notification from the database');

        return $instance;
    }
}
