<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserSelectionTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\UserSelectionType' shared autowired service.
     *
     * @return \App\Form\Type\UserSelectionType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Type\\UserSelectionType'] = new \App\Form\Type\UserSelectionType(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));
    }
}
