<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserDeleteSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\UserDeleteSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\UserDeleteSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/UserDeleteSubscriber.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventSubscriber\\UserDeleteSubscriber'])) {
            return $container->privates['App\\EventSubscriber\\UserDeleteSubscriber'];
        }

        return $container->privates['App\\EventSubscriber\\UserDeleteSubscriber'] = new \App\EventSubscriber\UserDeleteSubscriber($a);
    }
}
