<?php

namespace ContainerBUxxZaW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUx_TwigComponent_ComponentFactoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'ux.twig_component.component_factory' shared service.
     *
     * @return \Symfony\UX\TwigComponent\ComponentFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/ux-twig-component/src/ComponentTemplateFinder.php';

        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['ux.twig_component.component_factory'])) {
            return $container->privates['ux.twig_component.component_factory'];
        }

        return $container->privates['ux.twig_component.component_factory'] = new \Symfony\UX\TwigComponent\ComponentFactory(new \Symfony\UX\TwigComponent\ComponentTemplateFinder(($container->privates['twig.loader.native_filesystem'] ?? self::getTwig_Loader_NativeFilesystemService($container)), 'components/'), new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dossier' => [false, 'App\\Twig\\Components\\DossiersComponent', 'getDossiersComponentService', true],
            'dossierVRP' => [false, 'App\\Twig\\Components\\DossierVRP', 'getDossierVRPService', true],
            'dossiers_search' => [false, 'App\\Twig\\Components\\DossiersSearch', 'getDossiersSearchService', true],
            'dossiers_searchVRP' => [false, 'App\\Twig\\Components\\DossiersSearchVRP', 'getDossiersSearchVRPService', true],
        ], [
            'dossier' => '?',
            'dossierVRP' => '?',
            'dossiers_search' => '?',
            'dossiers_searchVRP' => '?',
        ]), ($container->privates['property_accessor'] ?? self::getPropertyAccessorService($container)), $a, ['dossierVRP' => ['key' => 'dossierVRP', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'method' => 'post', 'url_reference_type' => 1, 'service_id' => 'App\\Twig\\Components\\DossierVRP', 'class' => 'App\\Twig\\Components\\DossierVRP', 'template' => 'components/dossierVRP.html.twig'], 'dossier' => ['key' => 'dossier', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'method' => 'post', 'url_reference_type' => 1, 'service_id' => 'App\\Twig\\Components\\DossiersComponent', 'class' => 'App\\Twig\\Components\\DossiersComponent', 'template' => 'components/dossier.html.twig'], 'dossiers_search' => ['key' => 'dossiers_search', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'method' => 'post', 'url_reference_type' => 1, 'service_id' => 'App\\Twig\\Components\\DossiersSearch', 'class' => 'App\\Twig\\Components\\DossiersSearch', 'template' => 'components/dossiers_search.html.twig'], 'dossiers_searchVRP' => ['key' => 'dossiers_searchVRP', 'expose_public_props' => true, 'attributes_var' => 'attributes', 'live' => true, 'csrf' => true, 'route' => 'ux_live_component', 'method' => 'post', 'url_reference_type' => 1, 'service_id' => 'App\\Twig\\Components\\DossiersSearchVRP', 'class' => 'App\\Twig\\Components\\DossiersSearchVRP', 'template' => 'components/dossiers_searchVRP.html.twig']], ['App\\Twig\\Components\\DossierVRP' => 'dossierVRP', 'App\\Twig\\Components\\DossiersComponent' => 'dossier', 'App\\Twig\\Components\\DossiersSearch' => 'dossiers_search', 'App\\Twig\\Components\\DossiersSearchVRP' => 'dossiers_searchVRP']);
    }
}
