<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBUxxZaW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBUxxZaW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBUxxZaW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBUxxZaW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBUxxZaW\App_KernelDevDebugContainer([
    'container.build_hash' => 'BUxxZaW',
    'container.build_id' => '686e45bc',
    'container.build_time' => 1718352422,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBUxxZaW');
